// Mapping of city names to Craigslist subdomains
export const cityMap: Record<string, string> = {
    "New York City": "newyork",
    "San Francisco": "sfbay",
    "Los Angeles": "losangeles",
    "Chicago": "chicago",
    "Houston": "houston",
    "Phoenix": "phoenix",
    "Philadelphia": "philadelphia",
    "San Antonio": "sanantonio",
    "San Diego": "sandiego",
    "Dallas": "dallas",
    "San Jose": "sfbay",
    "Austin": "austin",
    "Jacksonville": "jacksonville",
    "Fort Worth": "dallas",
    "Columbus": "columbus",
    "Charlotte": "charlotte",
    "Indianapolis": "indianapolis",
    "Seattle": "seattle",
    "Denver": "denver",
    "Washington DC": "washingtondc",
    "Boston": "boston",
    "El Paso": "elpaso",
    "Nashville": "nashville",
    "Detroit": "detroit",
    "Oklahoma City": "oklahomacity",
    "Portland": "portland",
    "Las Vegas": "lasvegas",
    "Memphis": "memphis",
    "Louisville": "louisville",
    "Baltimore": "baltimore",
    "Milwaukee": "milwaukee",
    "Albuquerque": "albuquerque",
    "Tucson": "tucson",
    "Fresno": "fresno",
    "Mesa": "phoenix",
    "Sacramento": "sacramento",
    "Atlanta": "atlanta",
    "Kansas City": "kansascity",
    "Colorado Springs": "cosprings",
    "Miami": "miami",
    "Raleigh": "raleigh",
    "Omaha": "omaha",
    "Long Beach": "losangeles",
    "Virginia Beach": "norfolk",
    "Oakland": "sfbay",
    "Minneapolis": "minneapolis",
    "Tulsa": "tulsa",
    "Tampa": "tampa",
    "Arlington": "dallas",
    "New Orleans": "neworleans",
    "Wichita": "wichita",
    "Cleveland": "cleveland",
    "Bakersfield": "bakersfield",
    "Aurora": "denver",
    "Anaheim": "orangecounty",
    "Honolulu": "honolulu",
    "Santa Ana": "orangecounty",
    "Riverside": "inlandempire",
    "Corpus Christi": "corpuschristi",
    "Lexington": "lexington",
    "Stockton": "stockton",
    "Henderson": "lasvegas",
    "Saint Paul": "minneapolis",
    "St. Louis": "stlouis",
    "Cincinnati": "cincinnati",
    "Pittsburgh": "pittsburgh",
    "Greensboro": "greensboro",
    "Anchorage": "anchorage",
    "Plano": "dallas",
    "Lincoln": "lincoln",
    "Orlando": "orlando",
    "Irvine": "orangecounty",
    "Newark": "newjersey",
    "Toledo": "toledo",
    "Durham": "raleigh",
    "Chula Vista": "sandiego",
    "Fort Wayne": "fortwayne",
    "Jersey City": "newjersey",
    "St. Petersburg": "tampa",
    "Laredo": "laredo",
    "Madison": "madison",
    "Chandler": "phoenix",
    "Buffalo": "buffalo",
    "Lubbock": "lubbock",
    "Scottsdale": "phoenix",
    "Reno": "reno",
    "Glendale": "phoenix",
    "Gilbert": "phoenix",
    "Winston–Salem": "winstonsalem",
    "North Las Vegas": "lasvegas",
    "Norfolk": "norfolk",
    "Chesapeake": "norfolk",
    "Garland": "dallas",
    "Irving": "dallas",
    "Hialeah": "miami",
    "Fremont": "sfbay",
    "Boise": "boise",
    "Richmond": "richmond",
    "Baton Rouge": "batonrouge",
    "Spokane": "spokane",
    "Des Moines": "desmoines",
    "Tacoma": "seattle",
    "San Bernardino": "inlandempire",
    "Modesto": "modesto",
    "Fontana": "inlandempire",
    "Santa Clarita": "losangeles",
    "Birmingham": "birmingham",
    "Oxnard": "ventura",
    "Fayetteville": "fayetteville",
    "Moreno Valley": "inlandempire",
    "Rochester": "rochester",
    "Glendale (CA)": "losangeles",
    "Huntington Beach": "orangecounty",
    "Salt Lake City": "saltlakecity",
    "Grand Rapids": "grandrapids",
    "Amarillo": "amarillo",
    "Yonkers": "newyork",
    "Aurora (IL)": "chicago",
    "Montgomery": "montgomery",
    "Akron": "akroncanton",
    "Little Rock": "littlerock",
    "Huntsville": "huntsville",
    "Augusta": "augusta",
    "Port St. Lucie": "treasure",
    "Grand Prairie": "dallas",
    "Columbus (GA)": "columbusga",
    "Tallahassee": "tallahassee",
    "Overland Park": "kansascity",
    "Tempe": "phoenix",
    "McKinney": "dallas",
    "Mobile": "mobile",
    "Cape Coral": "fortmyers",
    "Shreveport": "shreveport",
    "Frisco": "dallas",
    "Knoxville": "knoxville",
    "Worcester": "worcester",
    "Brownsville": "brownsville",
    "Vancouver (WA)": "portland",
    "Fort Lauderdale": "miami",
    "Sioux Falls": "siouxfalls",
    "Ontario (CA)": "inlandempire",
    "Chattanooga": "chattanooga",
    "Providence": "providence",
    "Newport News": "norfolk",
    "Rancho Cucamonga": "inlandempire",
    "Santa Rosa": "sfbay",
    "Oceanside": "sandiego",
    "Salem": "salem",
    "Elk Grove": "sacramento",
    "Garden Grove": "orangecounty",
    "Pembroke Pines": "miami",
    "Peoria": "peoria",
    "Eugene": "eugene",
    "Corona": "inlandempire",
    "Cary": "raleigh",
    "Springfield (MO)": "springfield",
    "Fort Collins": "fortcollins",
    "Jackson": "jackson",
    "Alexandria": "washingtondc",
    "Hayward": "sfbay",
    "Lancaster": "losangeles",
    "Lakewood": "losangeles",
    "Clarksville": "nashville",
    "Palmdale": "losangeles",
    "Salinas": "monterey",
    "Springfield (MA)": "westernmass",
    "Hollywood (FL)": "miami",
    "Pasadena (TX)": "houston",
    "Sunnyvale": "sfbay",
    // Canada
    "Toronto": "toronto",
    "Montreal": "montreal",
    "Vancouver": "vancouver",
    "Calgary": "calgary",
    "Ottawa": "ottawa",
    "Edmonton": "edmonton",
    "Winnipeg": "winnipeg",
    "Quebec City": "quebec",
    "Hamilton": "hamilton",
    "Kitchener": "kitchener",
    "London (ON)": "londonon",
    "Victoria": "victoria",
    "Halifax": "halifax",
    "Oshawa": "toronto",
    "Windsor": "windsor",
    "Saskatoon": "saskatoon",
    "St. Catharines": "stcatharines",
    "Regina": "regina",
    "St. John's": "stjohns",
    "Barrie": "barrie",
    "Kelowna": "kelowna",
    "Brampton": "toronto",
    "Markham": "toronto",
    "Mississauga": "toronto",
    "Surrey": "vancouver",
    "Burnaby": "vancouver",
    "Richmond (BC)": "vancouver"
}

export { } 